### ISSUE TITLE
Why won't TerminateProcess work?

### ISSUE THREAD

**Issue by xorpd** [itm4n/PPLdump#5]
Hi, thanks for your research and for writing this util!
I played with the code, and was wondering whether if except for getting a memory dump it would be possible to kill a remote PPL protected process.

I tried to add a simple `TerminateProcess` call (with the handle of the remote process) at dllexploit.cpp but received an "access denied" error. I was wondering if I am doing something conceptually wrong? I expected that a PPL process will be able to terminate another PPL process.

**Comment by itm4n** [comment]
Hey!

You're right, you are not limited to dumping the memory of a PPL.

What you say is partially true but not completely accurate. Because PPLs have different protection levels, one PPL cannot necessarily access any other PPL. But in this particular case, it's not important because PPLdump injects code in a PPL running at `WinTCB` level, which is the highest level.

To answer your question, there may be a number of reasons why you get an "Access Denied" error.

- You didn't open the target process with the appropriate flag(s) (`PROCESS_TERMINATE`).
- The target process is protected at the Kernel level with a minifilter driver for instance.

My guess is you are trying to kill an AV/EDR process, so the second option is possible. :slightly_smiling_face:

**Comment by xorpd** [comment]
@itm4n Thanks for the very quick reply.
Your guess is indeed correct. I checked this on an AV process. I did open the process with the appropriate flags (`PROCESS_TERMINATE`), so it might be indeed a kernel level minifilter. I didn't even consider this option.
Thank you for your advice!
